@echo off
echo Starting Lead-Lag Backend (port 5000)...
start cmd /k "cd lead_lag/backend && python app.py"

echo Starting FX Backend (port 8001)...
start cmd /k "cd FX/backend && uvicorn main:app --port 8001 --reload"

echo Starting Lead-Lag Frontend (port 5173)...
start cmd /k "cd lead_lag/frontend && npm run dev"

echo All services starting...
